name: Azure Naija CI

on:
# When there is a commit to our master branch
 push:
    branches: main

jobs:
    docker: 
        runs-on: ubuntu-latest
        steps: 
            -
                name: Docker Login
                uses: docker/login-action@v3
                with:
                    username: ${{vars.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: Docker Login
                uses: docker/build-push-action@v5
                with:
                  context: .
                  push: true
                  tags: donhadley/chucknorris:latest
             


